### ISSUE TITLE
为什么启动时报这个错

### ISSUE THREAD

**Issue by tony1016** [csujedihy/proximac#1]
proximac start /etc/proximac.json 
Kernel extension cannot be loaded! Maybe it is already loaded so you have to unload it first. Or installing third-party kext is now allowed on your OS.

**Comment by csujedihy** [comment]
你是10.10的系统吧？

因为驱动是没有签名的，所以需要先执行这个命令```sudo nvram boot-args="debug=0x146 kext-dev-mode=1"```，打开驱动开发模式才能够加载驱动。
From:  tony1016
Reply-To:  csujedihy/proximac
Date:  Friday, August 21, 2015 at 12:16 AM
To:  csujedihy/proximac
Subject:  [proximac] 为什么启动时报这个错 (#1)


proximac start /etc/proximac.json 
Kernel extension cannot be loaded! Maybe it is already loaded so you have to unload it first. Or installing third-party kext is now allowed on your OS.

**Comment by csujedihy** [comment]
Note：执行命令```sudo nvram boot-args="debug=0x146 kext-dev-mode=1"```后，需要重启。
