### ISSUE TITLE
为何提示“env: python2: No such file or directory”？

### ISSUE THREAD

**Issue by luckypoem** [csujedihy/proximac#11]
hi。

我的mac是10.10.4版。我运行了sudo nvram boot-args="debug=0x146 kext-dev-mode=1"，也运行了
brew install libuv ，也运行了
curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python，

yudeMacBook-Air:~ yuming$ ls /usr/local/bin/
VBoxAutostart	autoupdate	glibtoolize	ras2tiff	tiffcp
VBoxBalloonCtrl	bmp2tiff	ifnames		raw2tiff	tiffcrop
VBoxDTrace	brew		isql		rdjpgcom	tiffdither
VBoxHeadless	ccmake		iusql		remake		tiffdump
VBoxManage	cjpeg		jpegtran	rgb2ycbcr	tiffinfo
VBoxVRDP	cmake		libpng-config	rscreen		tiffmedian
VirtualBox	cmakexbuild	libpng16-config	shadowvpn	tiffset
aclocal		cpack		node		slencheck	tiffsplit
aclocal-1.15	ctest		npm		sshuttle	tsocks
autoconf	djpeg		odbc_config	stunnel		vbox-img
autoheader	dltest		odbcinst	tcptunnel	vboxwebsrv
autom4te	duck		pal2rgb		thumbnail	wget
automake	event_rpcgen.py	png-fix-itxt	tiff2bw		wrjpgcom
automake-1.15	fax2ps		pngfix		tiff2pdf	wx-config
autoreconf	fax2tiff	ppm2tiff	tiff2ps		wxrc
autoscan	gif2tiff	proximac	tiff2rgba	wxrc-3.0
autossh		glibtool	proxychains4	tiffcmp 
yudeMacBook-Air:~ yuming$ proximac
env: python2: No such file or directory
yudeMacBook-Air:~ yuming$

如何解决？谢谢（我重启了系统，问题依旧）

**Comment by luckypoem** [comment]
我知道怎么解决了。
sudo ln -s /usr/bin/python /usr/bin/python2

**Comment by csujedihy** [comment]
good

**Comment by luckypoem** [comment]
hi.

不过翻墙速度不快，根本访问不了youtube.com,有什么办法解决吗

**Comment by csujedihy** [comment]
我原来测试没有这个问题哈

**Comment by iShawnWang** [comment]
666 ~ 3Q
