### ISSUE TITLE
proximac gets attached and detached constantly

### ISSUE THREAD

**Issue by robbielj** [csujedihy/proximac#12]
After running proximac, the console logs persistent socket attaching/detaching messages, like the following, several times a second

> kernel[0]: [Proximac]: Proximac TCP filter has been attached to a socket
> kernel[0]: [Proximac]: Proximac TCP filter has been detached from a socket

is this normal? OS is yosemite.

**Comment by csujedihy** [comment]
It's normal. Sorry for flushing your console.

**Comment by robbielj** [comment]
okay. not a big issue actually.
