### ISSUE TITLE
10.11.4 不能使用

### ISSUE THREAD

**Issue by vnexus** [csujedihy/proximac#13]
已执行sudo nvram boot-args="debug=0x146 kext-dev-mode=1"
proximac start -c /Users/ss.conf                   [10:02:43]
/usr/local/proximac/proximac.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
Kernel extension cannot be loaded! Maybe it is already loaded so you have to unload it first. Or installing third-party kext is not allowed on your OS.
qq:~/ $ proximac stop                                                [10:02:45]
No matching processes belonging to you were found
Proximac may not be started or may be killed accidentally.

**Comment by vnexus** [comment]
莫不是 brew install libuv这个没有安装 可是终端不走代理 
curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "pkg-config"
Download failed: https://homebrew.bintray.com/bottles/pkg-config-0.28.el_capitan.bottle.2.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz

curl: (28) Resolving timed out after 5539 milliseconds
Trying a mirror...
==> Downloading https://fossies.org/linux/misc/pkg-config-0.28.tar.gz

curl: (6) Could not resolve host: fossies.org

**Comment by csujedihy** [comment]
libuv没安装？

**Comment by vnexus** [comment]
@csujedihy   是没有装 因为终端不能走代理 brew连不上 .....

**Comment by vnexus** [comment]
@csujedihy  凑合者用http_proxy="socks://127.0.0.1"吧
