### ISSUE TITLE
I'm getting "env: python2: No such file or directory" error

### ISSUE THREAD

**Issue by bemike** [csujedihy/proximac#15]
I'm getting error message: env: python2: No such file or directory, when I tried to fire up proximac
I've tried to fix this by ln -sf /usr/local/bin/python2.7 /usr/local/bin/python2 but this didn't work.

Any other solution?

**Comment by csujedihy** [comment]
Could you try removing the first line in proximac.py?

**Comment by bemike** [comment]
@ csujedihy Never mind, I got it working. Turns out it was my mistake referring to the wrong path...
