### ISSUE TITLE
Will Python 3 support be added?

### ISSUE THREAD

**Issue by mofhu** [csujedihy/proximac#17]
Hi all,

Thanks for the great work here! I've been able to use ssh-based command line utils again by `proximac` in China.

By the way, I found that the `install.py` in `curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python` only supports python 2 (I swapped to py 2 to install it), and proximac is also only work in py 2, will py 3 be added in future?

I'd like to contribute (not recently, maybe after May 2016) python 3 support. However, I may not be able to work fast 😄 

Best,
Frank

**Comment by csujedihy** [comment]
Since python2 is the default python interpreter on Mac, I did not plan to support python3. If you can contribute a compatible version that supports both python2 and python3, that will be helpful.

**Comment by mofhu** [comment]
I see. I'll try it later in summer. Hope I can make it then 😄
