### ISSUE TITLE
I've got the kext signing cert

### ISSUE THREAD

**Issue by kinosang** [csujedihy/proximac#19]
Now we can sign the pre-build kext file and distribute it. Maybe we can use Travis CI for it.

**Comment by csujedihy** [comment]
I have purchased a Devmembership as well. Thank you so much! If you have any suggestion or idea, do not hesitate to share with me.

**Comment by kinosang** [comment]
If you want to use your Devmembership Cert to sing the kext, you should apply for it at https://developer.apple.com/contact/kext/

**Comment by arronmabrey** [comment]
Hey all, any progress on this front :-)

**Comment by csujedihy** [comment]
I heard that Apple simplifies the signing process on OSX 10 and Xcode 8. Is that true?

**Comment by kinosang** [comment]
I didn't hear that. And there's still restriction on kext signing.

**Comment by douglas** [comment]
Hello!

@csujedihy do the kext in the new releases are signed? I'm trying to use it to replace Proxifier, is it possible right now in macOS 10.12? Also, do I need to disable sip?

**Comment by csujedihy** [comment]
@douglas No, it does not but it works in 10.12 with disabled SIP.
