### ISSUE TITLE
请问可以支持HTTP吗？

### ISSUE THREAD

**Issue by venmos** [csujedihy/proximac#2]
请问可以支持HTTP吗？

**Comment by csujedihy** [comment]
支持不了http

**Comment by csujedihy** [comment]
你是说的http代理吗

**Comment by venmos** [comment]
en HTTP代理 上端可以用COW或者MEOW

**Comment by csujedihy** [comment]
这个是理论上做不到的吧？http代理只能用来代理http流量，其他流量是不能代理的吧。

**Comment by venmos** [comment]
Proxifier 和 redsocks 可以，我在翻番相关文档，  Thanks

**Comment by csujedihy** [comment]
目测应该是利用的https代理来发送二进制流量

**Comment by venmos** [comment]
嗯，应该是，这方面了解较少：）不管怎样，你的软件很好用，good job
