### ISSUE TITLE
`Cannot create fodler! ` error

### ISSUE THREAD

**Issue by Julyyq** [csujedihy/proximac#20]
I run `curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python` but get 'Cannot create fodler!' error.
My mac is 10.11.5. in recovery mode, i run successful with `csrutil enable --without kext --without debug`, and the libuv is already installed through homebrew.

How can i solve this error? Thanks in advance.

**Comment by csujedihy** [comment]
Permission problem? Try to use `sudo` to run the command.

**Comment by Julyyq** [comment]
The error still occurs: 
![screenshot 2016-07-28 08 58 49](https://cloud.githubusercontent.com/assets/2620575/17197683/8c77c3e6-54a1-11e6-9142-5d499454c490.png)

**Comment by quick-tutoriel** [comment]
Bonjour,

J'essaie d'installer le script et j'ai l'erreur : **Cannot create fodler!.**
J'exécute pourtant bien le script avec sudo.

Pouvez-vous m'aider ?

merci

**Comment by csujedihy** [comment]
@quick-tutoriel Thanks. I should revise the README.md to fix this error. Btw, better reply with english rather french.
