### ISSUE TITLE
Nice work, some issues...

### ISSUE THREAD

**Issue by bgiraffe** [csujedihy/proximac#23]
Hi, first of all, nice work! Thank you for the great app.
After i followed your instruction and start up by VPN mode, the following screenshot is the message
![screen shot 2016-08-25 at 01 26 46](https://cloud.githubusercontent.com/assets/230649/17940765/20c78924-6a63-11e6-899f-944561e55ef1.png)
Is that mean it is running ok? I found my chrome still need to browser facebook or youtube by switching on the ShadowsocksX "Global Mode" or "Auto Proxy Mode".
And can it run as background?

Looking forward to your reply, cheers~

**Comment by twiceyuan** [comment]
Just add option '-d'.

for example:
`proximac start -c proxy.conf -d`
