### ISSUE TITLE
Install Error : Cannot create fodler! 

### ISSUE THREAD

**Issue by iShawnWang** [csujedihy/proximac#24]
### I follow the install guide on README, when install ,i see following msg :

```
curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python
Cannot create fodler!
```
### env :
OS : 10.11.6 Mac Mini 2014 Late
csrutil disabled
shell : bash

**Comment by ubittibu** [comment]
tried running as root?

**Comment by iShawnWang** [comment]
Yep , i tried
`sudo curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python` 
with same error  `Cannot create fodler!`

**Comment by ubittibu** [comment]
try this.. download the script using your browser
https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py
(example: paste in safari address bar -> ENTER -> ALT+ENTER)
then from terminal:
`sudo python ~/downloads/install.py`

**Comment by iShawnWang** [comment]
WOW ~  works like a charm !
:D

**Comment by csujedihy** [comment]
I finally figure out why it didn't work. Should put sudo before python not in the front of the command.

**Comment by iShawnWang** [comment]
Got it ... Thanks for Your Great Works

? 2016?9?30??01:22?Jedihy <notifications@github.com<mailto:notifications@github.com>> ???

I finally figure out why it didn't work. Should put sudo before python not in the front of the command.

Sent from my iPhone

> On 29 Sep 2016, at 12:07 PM, Shuai Wang <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> WOW ~ works like a charm !
> :D
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-

**Comment by csujedihy** [comment]
Does proximac work on your computer?

**Comment by iShawnWang** [comment]
Can i Speak Chinese ?
Yes, I Can ~

--- 

我有ShadowSocksX ,然后配置文件用的你的 README 中的 VPN Mode

Console 
```
localhost:~ pi$ proximac start -c /Users/pi/Desktop/proximac.conf 
 2016-10-01 15:45:37 INFO: Proxy App name is ShadowsocksX
 2016-10-01 15:45:37 INFO: Hook Succeed!
 2016-10-01 15:45:37 INFO: All traffic will be redirected to this SOCKS5 proxy
 2016-10-01 15:45:37 INFO: Listening on 8558
```

我还要怎么测试他好不好用 ~?
