### ISSUE TITLE
macOS Sierra compatibility?

### ISSUE THREAD

**Issue by ubittibu** [csujedihy/proximac#25]
```
INFO: Hook Succeed!
INFO: All traffic will be redirected to this SOCKS5 proxy
INFO: Listening on 8558
```

Installed, configured and started, no error messages..  but idk where the traffic is redirected to.. apps cannot connect anymore.. 
My proxy is working, I tested it with FoxyProxy extension in Firefox.. but all the other application using proximac cannot connect to it..

macOS 10.12.0
Enabled SIP without kext and without debug

**Comment by csujedihy** [comment]
Some users found it is working under OSX 10.12

**Comment by NobelLiu** [comment]
10.12.1 not work too, without any warning or error.

**Comment by neeksor** [comment]
https://forums.developer.apple.com/thread/50380
