### ISSUE TITLE
无法后台运行

### ISSUE THREAD

**Issue by OscarGong** [csujedihy/proximac#28]
使用
```
 sudo proximac start -c ~/config.json &
```
后不会挂起，关掉 Terminal 后 Proximac 也随之关闭了

**Comment by OscarGong** [comment]
发现了有 -d 参数…

**Comment by csujedihy** [comment]
你能正常使用这个吗？

**Comment by csujedihy** [comment]
有一些用户反馈无法翻墙

**Comment by OscarGong** [comment]
@csujedihy 
可以的，Not in VPN mode，指定到 Surge 的 scocks 端口。

macOS 10.12.1, System Integrity Protection status: disabled.

**Comment by OscarGong** [comment]
只是在启动时会先提示一次  
```
INFO: Listen error INFO: Listen error
```
然后才会提示
```
INFO: Listening on 8558
```

另外通过 Proximac hook "LookupViewService" 依旧无法在 Mac look up 时使用 Wikipedia…

**Comment by csujedihy** [comment]
我是问能不能正常代理流量？

**Comment by OscarGong** [comment]
可以的。

**Comment by csujedihy** [comment]
哦，知道了，没看到上条

**Comment by csujedihy** [comment]
因为lookup是调用的一个rpc，你需要全局模式
