### ISSUE TITLE
为 kext 设置正确的权限

### ISSUE THREAD

**Issue by Vayn** [csujedihy/proximac#3]
今天更新代码之后重新 kextload proximac.kext，结果出现以下提示：

`/usr/local/share/proximac/proximac.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8).`

一开始以为是 dev mode 的原因

`sudo nvram boot-args` 发现 `kext-dev-mode` 已经设置好了。

查了一圈，原来必须要给 kext 设置以下权限：

`drwxr-xr-x  3 root  wheel`

chown & chmod 之后就可以 kextload 了。建议更新下使用说明。

**Comment by csujedihy** [comment]
因为新版使用方法变了

#### Usage 
1. If you plan to use Proximac on OSX 10.10+, please run ```sudo nvram boot-args="debug=0x146 kext-dev-mode=1"```. (Sorry, I do not have enough money to buy a developer membership to sign the kext)
1. Install libuv first. Run ```brew install libuv``` or whatever
2. Run ```curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python ```
3. Set up your config file which indicates Proximac's work mode (VPN or per-App) and proxy configuration
4. Run ```proximac start [path of your config file]``` to start Proximac
5. Run ```proximac stop``` to stop Proximac

在老版本的readme中友这么一句，```sudo chown -R root:wheel proximac.kext```

**Comment by csujedihy** [comment]
如果通过脚本一键安装```curl -fsSL https://raw.githubusercontent.com/proximac-org/proximac-install/master/install.py |python```，是不会出现权限问题。

**Comment by Vayn** [comment]
好的，没注意安装方法已经更新到自动化方式了。以后省事了:)

**Comment by csujedihy** [comment]
感谢反馈意见！
