### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by kkar** [csujedihy/proximac#30]
Hello, thanks for this project. Can be compiled and used in Windows Operating System?

**Comment by csujedihy** [comment]
No. Impossible for it to support win. However, you can find lots of alternatives for win.

Best regards,

Yi Huang

**Comment by kkar** [comment]
Sorry for asking in here, do you know any CLI proxification tool for windows? Everything i've found so far has a GUI and no-cli support at all. I need something like proximac or proxychains for windows with command line support. Thanks again!

**Comment by csujedihy** [comment]
Sorry, Idk.
