### ISSUE TITLE
not working for some programs?

### ISSUE THREAD

**Issue by paravar** [csujedihy/proximac#33]
my config file is like this: 

20:00 ~ >>cat .proximacrc 
{
    "process_name":
    ["Spotify", "Steam", "Hacker Menu", "Twitter", "twitter", "factorio", "App store", "Alternote", "Electron"],
    "local_port":1080,
    "local_address":"127.0.0.1",
    "proximac_port":8558,

}

For Spotify and "Hacker Menu", proximac seems to be working fine (since they don't work without socks5 where I am). But for Twitter & Steam it's not working. When I switch back to proxifier they work fine but not with proximac.
Thanks for any help in advance. I hope I can dump proxifier for good.

**Comment by csujedihy** [comment]
try to use VPN mode
