### ISSUE TITLE
Error while starting the program

### ISSUE THREAD

**Issue by euppi98** [csujedihy/proximac#36]
You get this error when you run the program:

> /usr/local/proximac/proximac.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
> Kernel extension cannot be loaded! Maybe it is already loaded so you have to unload it first. Or installing third-party kext is not allowed on your OS.

macOS 10.12.6 (16G1114)

**Comment by csujedihy** [comment]
It is not working in High Sierra.

**Comment by avral** [comment]
when will it be done for high sierra?

**Comment by csujedihy** [comment]
> when will it be done for high sierra?

I don't have a Mac anymore. So probably never.
