### ISSUE TITLE
Feature request - Any plans to add a GUI interface?

### ISSUE THREAD

**Issue by swatchion** [csujedihy/proximac#37]
Thanks for your great work. :)

Actually I am ok with terminal, but most people are not.

Just curious, if  a GUI interface will be added in future?

**Comment by csujedihy** [comment]
Is it still working on your Mac? I don't want to implement a GUI for this any more since I sold my Macbook and Apple does not want to further support and extend NKE that Proximac uses to provide traffic interception and forwarding. I had built a GUI but it is incomplete.

**Comment by csujedihy** [comment]
@jslatten 

Just found I still have it on github. It's far from complete.
https://github.com/csujedihy/proximac-gui
