### ISSUE TITLE
Proximac may not be able to work in OSX 10.11

### ISSUE THREAD

**Issue by csujedihy** [csujedihy/proximac#4]
If you still want to use proximac, stay away from OSX 10.11 until I figure out how to solve this problem.

The kext must be signed but I do not have Apple Dev Membership to do it. It's too expensive for a non-iOS developer....

**Comment by csujedihy** [comment]
Disable SIP, rootless, then it works!

**Comment by j7s3kab00** [comment]
in Recovery mode:
```
csrutil disable
```
https://forums.developer.apple.com/thread/3981

**Comment by kinosang** [comment]
I'm an Individual Apple Developer, and I've already apply for a kext signing certificate.

If the application approved, I can help you sign your pre-compiled kext file

**Comment by csujedihy** [comment]
Thank you! That will be great. So, what should I do next on the project?

**Comment by kinosang** [comment]
@csujedihy nothing before I get the entitlement, just do what you do normally. And I'll setup a CI to sign the kext after Apple approve my application.

**Comment by csujedihy** [comment]
Okay. Thank you!
