### ISSUE TITLE
Unable to authenticate on socks proxy with username and pass

### ISSUE THREAD

**Issue by Loriowar** [csujedihy/proximac#40]
Env:
- Mac OS 10.12.6
- Socks proxy based on Dante 1.4.2 with `username` auth method.

Problem: unable to authenticate at proxy server. Based on logs, client offer only `none` method:
```
debug: recv_methods(): client 109.***.***.***.11561 offered 1 authentication method: 0x0 (none)
```
Config for proximac include all required keys for auth (`username`, `password`) and this credentials works properly in browser proxy plugin.

Without authentication all works as expected: all traffic from app sent to proxy described in proximac config.

**Comment by csujedihy** [comment]
I am not able to debug this anymore since I do not own any Mac anymore. Anyway, the error looks like poximac user-space program does not well handle socks5 negotiation.

**Comment by Loriowar** [comment]
@csujedihy I found a problem. Please, look at #41. For more details you can look at [RFC1928](https://tools.ietf.org/html/rfc1928).

**Comment by csujedihy** [comment]
@Loriowar Merged. Thanks for the fix!
