### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by j7s3kab00** [csujedihy/proximac#5]
* OS X El Capitan
* my config:

```
{
    "local_port":9150,
    "local_address":"127.0.0.1",
    "proximac_port":8558,
    "VPN_mode":1,
    "proxyapp_name":"tor.real"
}
```
* starting:
 * 2015-10-08 21:21:35 INFO: Proxy App name is tor.real
 * 2015-10-08 21:21:35 INFO: Hook Succeed!
 * 2015-10-08 21:21:35 INFO: **All traffic** will be redirected to this SOCKS5 proxy
 * 2015-10-08 21:21:35 INFO: Listening on 8558

Checking my public IP:
```
$ curl ipecho.net/plain ; echo
OK.FOREIGN.IP.ADDRESS
```
```
$ dig +short myip.opendns.com @resolver1.opendns.com
MY.REAL.IP.ADDRESS!!!!!!!!
```

Maybe UDP traffic is not redirecting?

**Comment by csujedihy** [comment]
You are right! UDP is not redirected.


It will be in my todo list.




Sent with Unibox

**Comment by j7s3kab00** [comment]
Hello, again.

How can I help you in implementation UDP-functionality?
I have no experience in programming of kernel extensions but I have some skills in ios development.

**Comment by csujedihy** [comment]
Hey,


Glad to hear that. If you can write some code for user-space application proximac-cli to receive data from kernel, that will be very helpful. Proximac-cli is written in C using libuv. But if you can only write objc, maybe you can only write a UI for this program. Anyway, thanks a lot.


Sincerely,


Yi Huang




Sent with Unibox
