### ISSUE TITLE
Not able to start after upgrading OSX to 10.11 EI Capitan

### ISSUE THREAD

**Issue by liangsun** [csujedihy/proximac#6]
```
$  proximac start -c proximac.conf 
/usr/local/proximac/proximac.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
Kernel extension cannot be loaded! Maybe it is already loaded so you have to unload it first. Or installing third-party kext is now allowed on your OS.
```

**Comment by Vayn** [comment]
@csujedihy explained how to use `proximac` on OSX 10.10+:

> If you plan to use Proximac on OSX 10.10+, please run sudo nvram boot-args="debug=0x146 kext-dev-mode=1".

Please try again.

**Comment by liangsun** [comment]
@Vayn I tried. It doesn't work. It works on 10.10, but after I upgrading my system to 10.11, it doesn't work any more, even though I rerun `sudo nvram boot-args="debug=0x146 kext-dev-mode=1"`.

**Comment by csujedihy** [comment]
Try this:

in Recovery mode:
csrutil disable
https://forums.developer.apple.com/thread/3981

**Comment by liangsun** [comment]
@csujedihy It works. Thanks!
