### ISSUE TITLE
Usage steps of README is outdated and one of them makes me confused

### ISSUE THREAD

**Issue by holyshawn** [csujedihy/proximac#8]
The first step in 10.11 should like this:
Restart -> Press COMMAND + R -> Recovery Mode -> Terminal -> csrutil enable --without kext --without debug. 
("debug" is a personal choice for my other console program, I don't know whether it's essential or not.)

The fifth step should add a "-c" between "start" and the configure file path.

Your program works fine in my mac, thanks.

**Comment by csujedihy** [comment]
Okay! I will modify readme ASAP! Thank you!
